export class Ambience {
  private ctx:AudioContext|undefined;private gain:GainNode|undefined;private filter:BiquadFilterNode|undefined;private lastStep=0;private reverb:ConvolverNode|undefined;
  unlock():void {try{if(!this.ctx){const ctx=this.ctx=new AudioContext();this.gain=ctx.createGain();this.gain.gain.value=0;this.filter=ctx.createBiquadFilter();this.filter.type='lowpass';this.filter.frequency.value=450;const buffer=ctx.createBuffer(1,ctx.sampleRate*3,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const wind=ctx.createBufferSource();wind.buffer=buffer;wind.loop=true;wind.connect(this.filter);this.filter.connect(this.gain);this.gain.connect(ctx.destination);wind.start();this.reverb=ctx.createConvolver();const impulse=ctx.createBuffer(1,ctx.sampleRate*0.5,ctx.sampleRate),d=impulse.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length)**2;this.reverb.buffer=impulse;this.reverb.connect(this.gain);}void this.ctx.resume();}catch{}}
  update(time:number,speed:number,grounded:boolean,sector:string,surface:string,volume:number,active:boolean):void {
    const ctx=this.ctx;if(!ctx||!this.gain||!this.filter)return;this.gain.gain.setTargetAtTime(active?volume*0.05:0,ctx.currentTime,0.2);this.filter.frequency.setTargetAtTime(sector.includes('GROTT')?180:sector.includes('JARDIN')?650:420,ctx.currentTime,0.4);
    if(!active||!grounded||speed<1||time-this.lastStep<Math.max(0.18,0.5-speed*0.02))return;this.lastStep=time;
    const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=surface==='metal'?'triangle':'sine';osc.frequency.setValueAtTime(surface==='metal'?170:surface==='stone'?110:65,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(35,ctx.currentTime+0.09);gain.gain.setValueAtTime(volume*0.12,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(0.001,ctx.currentTime+0.12);osc.connect(gain);gain.connect(ctx.destination);if(sector.includes('GROTT')&&this.reverb)gain.connect(this.reverb);osc.start();osc.stop(ctx.currentTime+0.13);osc.onended=()=>{osc.disconnect();gain.disconnect();};
  }
}
